services:
  app:
    build: .
    env_file:
      - app.env
    volumes:
      - .:/usr/src/app/
    command:
      - scripts/start_app.sh
    ports:
      - "8000:8000"
  
  database:
    image: postgres:13.1
    env_file:
      - database.env 
    volumes:
      - database-data:/var/lib/postgresql/data/ 
volumes:
  database-data: 